FROM node:alpine

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json .

RUN npm install

# Copy all app files into the container
COPY . .

# Expose Vite's default dev server port
EXPOSE 5173

# Run the development server on host 0.0.0.0 to make it accessible
CMD ["npm", "run", "dev", "--", "--host","--port","5173"]
